language: objective-c
matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: osx10.11
      rvm: system

before_install:
  - if [ -f ".git/shallow" ]; then travis_retry git fetch --unshallow; fi
  - whoami
  - pwd
  - env
  - sudo chown -R $USER $(brew --repo)
  - brew update || brew update
  - mkdir -p $(brew --repo)/Library/Taps/homebrew
  - env | grep TRAVIS_
  - ln -s $PWD $(brew --repo)/Library/Taps/homebrew/hugh_test
  - cd $(brew --repo)/Library/Taps/homebrew/hugh_test
  - export TRAVIS_BUILD_DIR="$(brew --repo)/Library/Taps/homebrew/hugh_test"

script:
  - echo hello
  - mkdir build
  - cd build
  - cmake ..
  - make -j 4
  - ./hugh_test
  - brew install --verbose Test --tap=hughperkins/test-travis-osx
  - brew test --verbose Test --tap=hughperkins/test-travis-osx
  # - brew test-bot --tap=hughperkins/test-travis-osx

notifications:
  email:
    on_success: never
    on_failure: never
